{% set name = "npx" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be8c1cf9afd74682cd19e2ca2fad89e80de8020772fc2fcf771f37bcce7a94f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - importlib_metadata
    - numpy

test:
  imports:
    - npx
  requires:
    - exdown
    - pytest
  source_files:
    - README.md
    - tests
  commands:
    - python -m pytest

about:
  home: https://github.com/nschloe/npx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Useful fixes and extensions for NumPy
  dev_url: https://github.com/nschloe/npx

extra:
  recipe-maintainers:
    - nschloe
